apiVersion: v1
kind: Pod
metadata:
  name: glowphonic-zig-dev
  namespace: mhudasch-glowphonic
  labels:
    app: glowphonic
spec:
  containers:
  - name: dev
    image: glowphonic-zig-dev:latest
    imagePullPolicy: Never  # Use local image
    command: ["sleep", "infinity"]
    resources:
      requests:
        memory: "1Gi"
        cpu: "500m"
      limits:
        memory: "2Gi"
        cpu: "1"
    volumeMounts:
    - name: workspace
      mountPath: /workspace
    - name: git-config
      mountPath: /home/vscode/.gitconfig
      readOnly: true
    - name: ssh
      mountPath: /home/vscode/.ssh
      readOnly: true
    securityContext:
      privileged: true  # For debugging tools
  volumes:
  - name: workspace
    hostPath:
      path: "/mnt/c/Users/Martin/.code/00_Home/2025/glowphonic"
  - name: git-config
    hostPath:
      path: "/home/martin/.gitconfig"
  - name: ssh
    hostPath:
      path: "/home/martin/.ssh"
